query actors {
  actors {
    id
    firstName
    lastName
  }
}

query musicals($limit: Int = 10) {
  musicals(limit: $limit) {
    id
    name
    imageSource
  }
}

input PreferenceInput
{
  musicals: [Int!]!
  actors: [Int!]!
  withChildren: Boolean
}

query musicalsByPreference($preference: PreferenceInput) {
  musicalsByPreference(preference: $preference) {
    id
    name
  }
}

query musicalById($id: ID) {
  musicalById(id: $id) {
    id
		name
    theatre {
      webURL
    }
    actors {
      firstName
      lastName
      birthDate
    }
  }
}